#!/bin/sh

#./bashExamples $(ls)
# also maybe like add that array thingy

# flags management
LC_SC_DRYRUN=false
	# initialise options
	for arg in "$@"; do
		case "$arg" in
			-d|--dry)
				LC_SC_DRYRUN=true
				;;
		esac
	done

# init like this
declare -A apps=(
["aap"]="8001:8000"
["aau"]="8000:80"
["asp"]="8004:3003"
)
# or like this
apps["axp"]="8003:5000"
apps["acp"]="8002:3002"

for app in "${!apps[@]}"; do
	echo "${apps[$app]}"
done

echo "starting program at $(date)"

echo "Running program $0 with $# arguments and pid: $$"

for arg in "$@";do
  grep todo "$arg" > /dev/null 2> /dev/null
  # if the file contains a todo then grep has exit status
  # then we redirect STDOUT and STDERR to a null register
  if [[ "$?" -ne 0 ]];then
    echo "File $arg does not have any todo in it"
  fi
done


# touch with recursive parents
tfile="/tmp/tTempteastetDIR/some/path/that/wasnt/there/before/fffffileeee"
mkdir -p "${tfile%/*}" && touch "$tfile"
mkdir -p "${tfile%/*}" && echo "this file and its parents is new" > "$tfile"

# named parameters?
setupWindow() {
  local dir name start=false
  local "${@}"
  echo "$dir $name $start"
  $start && echo "started!!"
}
setupWindow name=aap start=true dir=~/















echo "The End"
