#!/bin/sh

if [ $# -eq 0 ]; then
  echo cut what myre?
  exit 1;
elif [ $# -ne 1 ];then
  echo more than one argument specified!!
  exit 1;
fi

secs=$(ffmpeg -i "$1" 2>&1 | grep Duration | cut -d ' ' -f 4 | sed s/,// | sed 's@\..*@@g' | awk '{ split($1, A, ":"); split(A[3], B, "."); print 3600*A[1] + 60*A[2] + B[1] }')

ext=$(echo "$1" | cut -d '.' -f2)

echo "$secs"

for i in $(seq 0 $((secs/30 + 1)));do
  echo "-ss $((i*30)) -t 30 ->"
  ffmpeg -i "$1" -ss $((i*30)) -t 30 part-"$i"."$ext"
done;
