#!/bin/sh

pid=$(ps -au $USER -o pid,%mem,%cpu,tty,comm | sort -brk2 | sed -n '1!p' | dmenu -i -l 15 | awk '{print $1 " " $5}')
pname=$(echo $pid | awk '{print $2}')
pid=$(echo $pid | awk '{print $1}')
if [ -n $pid ]; then
  exit
fi
kill $pid
#kill -15 $pid 2>/dev/null
notify-send $pname' killed'
