#!/bin/sh

action=$(echo -e "Install\nRemove\nUpgrade\nClean" | dmenu -p "sofman: " -i)

case $action in
  "Install")
    package=$(pacman -Si |
      awk '/^Name/{name=$3} /^Download Size/{ds=$4$5} /^Repository/{repo=$3} /^Description/{sub(/^.{18}/,"", $0); print name,  "["ds"]" , "("repo") => ", $0}' |
      sort -d | dmenu -i -l 25 | awk '{print $1}')

    echo $package
    sudo pacman -S --noconfirm $package
    notify-send $package' installed'
    ;;
  "Remove")
    package=$(pacman -Qi |
      awk '/^Name/{name=$3} /^Installed  Size/{ds=$4$5} /^Repository/{repo=$3} /^Description/{sub(/^.{18}/,"", $0); print name,  "["ds"] => ", $0}' |
      sort -d | dmenu -i -l 25 | awk '{print $1}')

    echo $package
    sudo pacman -R --noconfirm $package
    notify-send $package' removed'
    ;;
  "Clean")
    sudo pacman -Rs $(pacman -Qqtd)
    notify-send 'unused dependencies go brr'
    ;;
  "Upgrade")
    sudo pacman -Syu --noconfirm
    notify-send 'Arch is locked and rolling'
    ;;
  *)
    notify-send 'nah'
    ;;
esac
